trigger:
  branches:
    include:
    - master
  paths:
    include:
    - ydawgie-azure-single-keyvault/central/generated/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    terraform init -backend-config=./backend.tfvars
  displayName: 'terraform init'

- script: |
    terraform plan -var-file=./terraform.tfvars
  displayName: 'terraform plan'

- script: |
    terraform apply -var-file=./terraform.tfvars
  displayName: 'terraform apply'
