trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  group: 'spk-infra-hld-vg'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: $(SPK_PROJECT_ID)
    definition: $(SPK_DEFINITION_ID)
    buildVersionToDownload: 'latestFromBranch'
    branchName: 'refs/heads/master'
    itemPattern: "spk*"
    artifactName: 'spk_linux_node_12'
    targetPath: '$(System.DefaultWorkingDirectory)'
- bash: |
    shopt -s expand_aliases
    echo "Current Dir is $(pwd)"
    chmod +x spk-linux
    alias spk="$(pwd)/spk-linux"
    spk --version
  displayName: "Verify SPK downloaded and executable"
  failOnStderr: true

- bash: |
    curl $BEDROCK_BUILD_SCRIPT > build.sh
    chmod +x ./build.sh
  displayName: Download Bedrock orchestration script
  env:
    BEDROCK_BUILD_SCRIPT: https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/build.sh

- script: |
    dpkg --configure -a
    curl -sL https://aka.ms/InstallAzureCLIDeb | bash
    az --version
  displayName: 'Install az-cli'

- script: |
    . build.sh --source-only
    init
    get_os_spk
    get_spk_version
    download_spk
    echo 'SPK Version: '
    spk --version
    echo "GENERATING ydawgie-azure-single-keyvault"
    cd ydawgie-azure-single-keyvault
    spk infra generate -p west
  displayName: 'SPK'

- script: |
    wget https://releases.hashicorp.com/terraform/$(tf_version)/terraform_$(tf_version)_linux_amd64.zip -q
    unzip -q terraform_$(tf_version)_linux_amd64.zip
    sudo mv terraform /usr/local/bin
    terraform -version
  displayName: 'Install Terraform'

- script: |
    terraform plan -var-file=./spk.tfvars
  displayName: 'Terraform init'

- script: |
    terraform plan -var-file=./spk.tfvars
  displayName: 'Terraform plan'

- script: |
    git clone $GENERATED_REPO
    cp -r dev-generated spk-infra-generated/find/
    cd spk-infra-generated/find

    #Set git identity
    git config user.email "admin@azuredevops.com"
    git config user.name "Automated Account"

    # Following variables have to be set for TeamCity
    export GIT_AUTHOR_NAME="Automated Account"
    export GIT_COMMITTER_NAME="Automated Account"
    export EMAIL="admin@azuredevops.com"

    cd dev-generated/west
    git status
    git add .
    git commit -m "Adding generated components"
    git push $GENERATED_REPO
  displayName: 'Commit and Push to Generated Repository'
